### ISSUE TITLE
Pending new concepts from STSCI

### ISSUE THREAD

**Issue by katieefrey** [astrothesaurus/UAT#268]
Continued from #267 , via Jenny Novacescu

| Suggested Concept | Note |
| --- | --- |
| Spectral Energy Distribution | |
| Radio AGN | Relationship between "radio cores" and "Radio AGN" unclear |

**Comment by katieefrey** [comment]
SED added as a concept, child of "Photometry" will be in the next release.

@stlibrary18 I want to include Radio AGN, but want to make sure it doesn't overlap with radio cores... As I've been looking into this I'm also coming across terms like "radio-loud AGN" and "radio-quiet AGN."  Do you think there is an interest in those concepts?  Would they be better than a plain "radio AGN"?

**Comment by stlibrary8** [comment]
The literature suggests "radio-quiet" and "radio-loud" are classes of radio AGN. Radio AGN are not a widely studied concept among STScI staff so I can't think of who to ask at this institution, but it is a concept that is selected for some Hubble proposals. I think if "radio-loud AGN" and "radio-quiet AGN" are added, these should be treated as child terms to the more generic "radio AGN" since the loud and quiet are considered classes of AGN. I would not add quiet and loud without the broader "radio AGN" parent term since some research is done broadly on radio AGN without focusing on a single class.

**Comment by katieefrey** [comment]
I've added Radio AGN, but not the quiet or load classes at this time.  Will be in the next release.
