### ISSUE TITLE
Add concepts under Galaxy clusters, submitted by Sarah Weissman (STScI) 8/11/2016 

### ISSUE THREAD

**Issue by katieefrey** [astrothesaurus/UAT#27]
Galactic and extragalactic astronomy->Galaxy clusters
->Rich clusters
->Poor clusters
->High-redshift clusters

**Comment by katieefrey** [comment]
Do these concepts mean something out of the context of the hierarchy? To avoid potential confusion with star clusters, I propose "Rich galaxy clusters," "Poor galaxy clusters," and "High-redshift galaxy clusters."

**Comment by seweissman** [comment]
Rich/poor is a widely used morphological classification for galaxy clusters. (http://www.astro.cornell.edu/academics/courses/astro201/galaxies/clus.htm) I think it's fine to use rich galaxy clusters, etc. as the preferred term, but probably we should include rich clusters, etc. as non-preferred terms just because these terms are used so commonly. Or is that still too confusing?

**Comment by katieefrey** [comment]
accepted.

"Rich galaxy clusters," "Poor galaxy clusters," and "High-redshift galaxy clusters" added as child of "Galaxy clusters."  NPT versions without the word galaxy also added for each concept.
