### ISSUE TITLE
Modify Concept: Biomarkers

### ISSUE THREAD

**Issue by katieefrey** [astrothesaurus/UAT#271]
**Name the concept in question**
Biomarkers
http://astrothesaurus.org/uat/2018

**Describe the change**
Andrew Siemion mentioned "biosignature" to me as a concept that feels equivalent to "biomarkers."   How does "biomarkers" relate to "biosignatures"? are they the same concept, which is preferred?  Also, want to check with STSCI folk who suggested biomarker in the first place.

**Comment by stlibrary8** [comment]
Hi Katie, Biomarkers and Biosignatures are synonymous in the way they are used for proposal purposes. I did a brief search in ADS and both forms have about the same # of results. This is because you can see from this search they are treated already as synonyms in the astronomy database of ADS: https://ui.adsabs.harvard.edu/search/filter_database_fq_database=AND&filter_database_fq_database=database%3A%22astronomy%22&fq=%7B!type%3Daqp%20v%3D%24fq_database%7D&fq_database=(database%3A%22astronomy%22)&q=full%3A(biosignature%20OR%20biosignatures)&sort=date%20desc%2C%20bibcode%20desc&p_=0.  With this in mind, it seems anecdotally that Biosignatures is a more preferred form in recent years based on the ADS search results, but no more or less hierarchical than Biomarkers. If you want to change the human readable form associated with http://astrothesaurus.org/uat/2018 to "Biosignatures" as the Preferred term and "Biomarkers" as an added _Use For_, I am okay with that change.

**Comment by katieefrey** [comment]
Accepted as biomarkers.  See also #269 & #270
