### ISSUE TITLE
Deprecate Concept: Cometary studies

### ISSUE THREAD

**Issue by mkelley** [astrothesaurus/UAT#275]
**Name the concept in question**
279 Cometary studies

**Why should the concept be deprecated?**
There are ways in which comets interact with, e.g., the solar wind, but cometary interiors, atmospheres are not an interplanetary concept unless planet interiors and atmospheres are considered one.  In addition, cometary studies are particular to comets, not the interplanetary medium / space.

**Child concepts?**
Dirty snowball theory - I recommend model rather than theory.  It could be placed under:
-> Solar system astronomy | Solar system | Small solar system bodies | Comets
or
-> Solar system astronomy | Solar system | Small solar system bodies | Comets | Nucleus
The latter may be better since it is most specific to the nucleus structure?

Comet interiors
-> Solar system astronomy | Solar system | Small solar system bodies | Comets | Nucleus | Interior

Cometary atmospheres
-> Solar system astronomy | Solar system | Small solar system bodies | Comets | Atmosphere

Cometary ionospheres
-> Solar system astronomy | Solar system | Small solar system bodies | Comets | Ionosphere
or
-> Solar system astronomy | Solar system | Small solar system bodies | Comets | Atmosphere | Ionosphere
for symmetry with Solar system astronomy | Planetary science | Planetary atmospheres | Earth atmosphere | Ionosphere

**Please include any additional comments/feedback**
Perhaps there is some reasoning for Cometary studies in this location, but it isn't obvious to me.

**Comment by stlibrary8** [comment]
I have the following recommendations from John Stansberry and Bryan Holler at Space Telescope Science Institute, very much in line with Mike Kelley's:

1. Deprecate vague "Cometary studies" term from UAT and replace with following terms:

Solar system astronomy | Solar system | Small solar system bodies | Comets

Per John: "Comets | Atmosphere strikes me as strange. Atmosphere typically refers to gravitationally bound gas with a well-defined surface pressure. I'm unaware that any comet has ever been observed to have one. They do have comae, and the gas in the coma transitions from neutral to charged (becoming the ionosphere, I guess). So I might suggest:
o	Comets | coma
o	Comets | coma | gas
o	Comets | coma | gas | neutral
o	Comets | coma | gas | ionized
o	Comets | coma | dust

•	Re nucleus, interior, this seems reasonable to me: 
o	Comets | nucleus
o	Comets | nucleus | surface
o	Comets | nucleus | interior
o	Comets | nucleus | volatiles  (usually volatiles imply the ice component, not gas)

Other terms that should exist:
o	Comets | main-belt comets
o	Comets | Dirty Snowball Model
* If Mike Kelley feels strongly Comets | nucleus | Dirty Snowball Model is best, this is fine, since it is understood the model mostly applies to nucleus formation.

**Comment by katieefrey** [comment]
It looks like "Cometary atmospheres" (275) was used in literature in the 80s and early 90s, and it has shifted to "coma."  How about deprecate 275, and use "cometary atmospheres" as an NPT of "Comas" (271)?   Is "comas" or "comae" preferred?

I'd prefer to leave "Dirty snowball model" somewhere in the "theory/process" side of Solar system astronomy (rather than the more "object" oriented side), but the only potential place I see is "Planetary science" and I'm don't really think it's a good fit there, so it might have to live as a child of "Comets", as suggested above.

**Comment by stlibrary8** [comment]
Agree with retaining "cometary atmospheres" as NPT since used historically. ADS search shows that "comae" is more prevalent than comas.

**Comment by katieefrey** [comment]
I trimmed down the comae section a tad, hows this?

Comets|Comae
Comets|Comae|Comae dust
Comets|Comae|Neutral coma gases
Comets|Comae|Ionized coma gases
Comets|Comet nucleus
Comets|Comet nucleus|Comet interior
Comets|Comet nucleus|Comet surface
Comets|Comet nucleus|Comet volatiles
Comets|Dirty snowball model
Comets|Main-belt comets

**Comment by katieefrey** [comment]
Changes implemented as described in my previous reply.  Cometary studies will be deprecated.  Changes will be in the next release.

**Comment by mkelley** [comment]
Thanks for this work and discussion!
