### ISSUE TITLE
Add concept: Atmospheric transmission, submitted by Megan Potterbusch (CfA) 9/25/2015

### ISSUE THREAD

**Issue by katieefrey** [astrothesaurus/UAT#28]
Popular term according to searches. ADS search yields over 10K results.
Supporting Links:
http://labs.adsabs.harvard.edu/adsabs/search/?q=%22Atmospheric+transmission%22&month_from=&year_from=&month_to=&year_to=&db_f=%28astronomy+OR+physics%29&nr=&bigquery=

**Comment by katieefrey** [comment]
2.3k results (1k refereed)
https://ui.adsabs.harvard.edu/search/q=%22Atmospheric%20transmission%22&sort=date%20desc%2C%20bibcode%20desc&p_=0

relates to observing exoplanet (and exomoon) atmospheres

**Comment by stlibrary8** [comment]
Recommend placement as follows since the technique  has been used to analyze Earth's atmosphere too. Don't believe this needs to live specifically under Exoplanets as its more about observational technique than class of object, but can understand if final decision ends up placing it polyhierachically under Observational Astronomy _and_ Exoplanet Astronomy top terms.

Observational Astronomy --> Astronomical Techniques --> Spectroscopy --> Transmission Spectroscopy

Add UF non-preferred term as follows: Atmospheric Transmission

**Comment by katieefrey** [comment]
I think it makes the most sense to leave it under observational techniques.  Added, will be in the next release.
