### ISSUE TITLE
New Concept: Cold Neptunes

### ISSUE THREAD

**Issue by katieefrey** [astrothesaurus/UAT#284]
**Name the new concept**
Cold Neptunes

**Describe the concept**
If Hot Neptunes are a category, it seems reasonable that
there should be a category for Cold Neptunes.

**Describe where the concept fits within the existing hierarchy**
Child of Exoplanets, sibling of Hot Neptunes

**Provide 1-3 supporting articles**
We are publishing a paper with the first discovery of al Cold Neptune.

**Please include any additional comments/feedback**

Suggestion from Paul Butler, Staff Scientist, Carnegie Institution for Science, Department of Terrestrial Magnetism

**Comment by katieefrey** [comment]
227 hits for "Hot Neptunes" in ADS vs 11 for "Cold Neptunes"

**Comment by stlibrary8** [comment]
Katie, I've asked for feedback and not heard back. For what it's worth, in poking around ADS, I agree with Paul Butler that "Cold neptunes" seems to be a term in its own right in exoplanet research and should be added. Not a problem if you want further confirmation from exoplanet researchers for a future (2020 release) instead of adding now.

**Comment by katieefrey** [comment]
I've gone ahead and added it.  I agree that it is a term in its own right, and it will probably see more growth as our ability to study exoplanets increases.

Will be in next release.
