### ISSUE TITLE
Modify Concept: Quasar microlensing in context of Exoplanet detection methods

### ISSUE THREAD

**Issue by rpoleski** [astrothesaurus/UAT#287]
**Name the concept in question**
Quasar microlensing - 1318

**Describe the change**
Quasar microlensing appears in 2 places in hierarchy:
1. Astrophysical processes	-> Gravitation -> General relativity	-> Gravitational lensing -> Gravitational microlensing -> Quasar microlensing
2. Exoplanet astronomy ->  Exoplanet detection methods -> Gravitational microlensing -> Quasar microlensing

The first one is correct, but the second is misleading. We use gravitational microlensing for exoplanet detection, but not in quasars. Thus, I propose to remove "Quasar microlensing" from the second place in hierarchy (and keep untouched both the first Quasar microlensing and the Gravitational microlensing as Exoplanet detection method).

**Please include any additional comments/feedback**

None

**Comment by katieefrey** [comment]
Thanks for this feedback!  I agree that this isn't exactly right, but it's not been easy to come up with the right solution.  Is quasar microlensing properly a type of gravitational microlensing?  or could they be siblings?

In the UAT, if a concept has a child, it must have that child everywhere it appears, so your exact suggestion as written isn't feasible.

something like this:

- Astrophysical processes -> Gravitation -> General relativity -> Gravitational lensing -> Gravitational microlensing

- Astrophysical processes -> Gravitation -> General relativity -> Gravitational lensing ->  Quasar microlensing

- Exoplanet astronomy -> Exoplanet detection methods -> Gravitational microlensing

**Comment by rpoleski** [comment]
I think this is a good solution.

**Comment by rpoleski** [comment]
One more similar case:

Exoplanet astronomy -> Exoplanet detection methods -> Astrometry -> ...

and then follows a hierarchy of ~130 terms, which includes "Solar eclipses", "Standard candles", "Cepheid distance" etc. I propose to change it to:

Exoplanet astronomy -> Exoplanet detection methods -> **Astrometric planet detection**

and no deeper hierarchy.

**Comment by rpoleski** [comment]
Following my last comment, I think it should be considered to change:

Exoplanet astronomy -> Exoplanet detection methods -> Gravitational microlensing

to:

Exoplanet astronomy -> Exoplanet detection methods -> Gravitational microlensing **planet detection**

I note that soon I'll propose a longer list of terms related to "gravitational microlensing".

**Comment by katieefrey** [comment]
Since in your opening comment you said that quasar microlensing sense a child of gravitaitonal microlensing, how about this...

Astrophysical processes -> Gravitation -> General relativity -> Gravitational lensing -> Gravitational microlensing -> Quasar microlensing
Astrophysical processes -> Gravitation -> General relativity -> Gravitational lensing -> Gravitational microlensing -> Gravitational microlensing planet detection
Exoplanet astronomy -> Exoplanet detection methods -> Gravitational microlensing planet detection

This gives them a parent/child relationships.  Alternatively, "Gravitational microlensing" and "Gravitational microlensing planet detection" could only be linked as "related terms," but I think the parent/child would work.

**Comment by katieefrey** [comment]
Resolved in #310.  Astrometric planet detection also added.
