### ISSUE TITLE
New Concepts: Exoplanet system formation [(PT]) and Protoplanetary disks [Extrasolar] (CT)

### ISSUE THREAD

**Issue by stlibrary8** [astrothesaurus/UAT#309]
Exoplanet system formation
Protoplanetary disks [Extrasolar]

Please note "Protoplanetary disks [Extrasolar]" may be a little premature; not a ton in the literature yet, but some articles exist and more expected with JWST launch.

Currently, there is no way to describe study of protoplanetary disks specific to Exoplanet systems, only a Solar system equivalent exists in UAT.

Proposed Hierarchy:
Exoplanet astronomy
...Exoplanet systems
......Exoplanet system formation (proposed term)
......... Protoplanetary disks [Extrasolar] (proposed term)
(also propose "Use For: Protoplanetary discs [Extrasolar])

Supporting literature, specific to "Protoplanetary disks [Extrasolar]":
https://ui.adsabs.harvard.edu/abs/2007MNRAS.380.1737W/abstract
https://ui.adsabs.harvard.edu/abs/2009AIPC.1158..333H/abstract
https://ui.adsabs.harvard.edu/abs/2010koa..prop..268K/abstract (Keck proposal)
https://ui.adsabs.harvard.edu/abs/2018cosp...42E.670C/abstract

**Comment by katieefrey** [comment]
I think the current concept breaks the strict separation that's existed between the Solar system and exoplanetary systems...

The existing "Protoplanetary disks" concept is a child of:
Interplanetary medium
Circumstellar disks
Protostars
Planetary system formation

Which says, to me, that this concept is not specific to our system, but is a more general concept... Should we differentiate between "our" protoplanetary disk and others in the galaxy?

**Comment by stlibrary8** [comment]
Hi Katie, I was looking through ADS and I don't feel we need to be that specific, meaning protoplantary disks for "our" solar system. However, in my understanding of the UAT right now, the child term "Protoplanetary disks" when placed under "Solar system astronomy"... "Planetary system formation" and "Solar system astronomy"... "Interplanetary medium" already implies "our" protoplanetary disk when in these parts of the UAT hierarchy, whereas "Protoplanetary disks" as a child term of Circumstellar disks or Protostars is more general. Maybe the way I'm interpreting the UAT is incorrect? 

Anyway, if my understanding is correct, then I agree we don't need Protoplanetary disks [Extrasolar]. The child term of Protostars and Circumstellar disks is basically the same as Protoplanetary disks [Extrasolar]. Perhaps we could just add UF: _Protoplanetary disks [Extrasolar]_ under the child term of Protostars and Circumstellar disks?

**Comment by katieefrey** [comment]
"Protoplanetary disks" is the same concept in all locations; it's all http://astrothesaurus.org/uat/1300

Since it is found under both "Solar system --> Planetary system formation" and "Interplanetary medium," the concept (1300) is not specific to either the Solar system's disk or disks from extrasolar systems, it can and should be used for both.

The main reason we have concepts like "Solar flare" is because it is seen as important to the astronomical community distinguish those from other star's flares.  As you say, there isn't that same need to distinguish the Solar system protoplanetary disk from other protoplanetary disks, so we use can use the generic concept of a "protoplanetary disk."

I can add _UF: Protoplanetary disks [Extrasolar]_ to the concept, which will appear as a NPT at all locations of the hierarchy for 1300.   I think that is fine since, as I stated above, the concept isn't specific and there doesn't seem to be a real need to call out the solar systems disk separately.
