### ISSUE TITLE
New Concept: Common Envelope Episodes/Stellar Mergers

### ISSUE THREAD

**Issue by morganemacleod** [astrothesaurus/UAT#311]
**Common Envelope Episodes and Merging Stars**
Two suggested concepts under Interacting Binary Stars

**Describe the concept**
This concept is related to the Stellar astronomy branch and especially the Binaries concept. 

Common envelope episodes: this is a form of binary star interaction that occurs in close binaries when one star engulfs its companion, and the two stellar cores spiral closer within a shared envelope. 

Merging stars:  when a close pair of stars merge. 

**Describe where the concept fits within the existing hierarchy**
Stellar astronomy 
Stellar types
Multiple stars
Binary stars
Close binary stars
Interacting binary stars
--> Suggestion: Common Envelope Episodes
--> Suggestion: Merging stars

**Provide 1-3 supporting articles**
Nearly 2000 results on ads for "common envelope", of these a few examples:
https://ui.adsabs.harvard.edu/abs/1976IAUS...73...75P/abstract
https://ui.adsabs.harvard.edu/abs/2000ARA%26A..38..113T/abstract
https://ui.adsabs.harvard.edu/abs/2013A%26ARv..21...59I/abstract

One recent example for stellar mergers:
https://ui.adsabs.harvard.edu/abs/2019Natur.574..211S/abstract

**Please include any additional comments/feedback**

**Comment by katieefrey** [comment]
@morganemacleod 

As written "Common Envelope Episodes" sounds like a physical process or event, rather than a specific type of binary star.  This is what I am envisioning:

1) Use the concept "Common envelope binaries" as seen in the title of 1976IAUS...73...75P, as a child of "Interacting binary stars."
2) Find a place for "Common envelope episodes" (and/or "evolution"?) under the "Stellar physics" section or perhaps somewhere near "Roche limit" and "Roche lobe" (these two are found under the main branch of "Astrophysical processes").
3) Link "Common envelope binaries" to "episodes" (and/or "evolution"?) as "related terms."

You can use the [Hierarchy Browser](http://astrothesaurus.org/thesaurus/hierarchical-browse/) or [Sorting Tool](https://uat.wolba.ch/) to explore the "Stellar physics" and "Astrophysical processes" branches in more detail.

Merging stars seems well supported in the literature as "stellar mergers."  I think it would be fine to include under "Interacting binary stars."

**Comment by morganemacleod** [comment]
@katieefrey 

Thank you! I think the three items you outlined above sound ideal. Thanks for your feedback on how to rephrase these, I completely agree that "Common envelope binaries" is a good phrasing. 

Find a place for "Common envelope episodes" (and/or "evolution"?) under the "Stellar physics" section or perhaps somewhere near "Roche limit" and "Roche lobe" (these two are found under the main branch of "Astrophysical processes").

Common envelope evolution and episodes are used about equally and somewhat interchangeably to my knowledge. In the context of defining a "Stellar Physics" Process I wonder if "Common Envelope Evolution" makes more sense. 

One Possibility is 
Stellar Physics 
Stellar Evolution
Binary/Multiple Star Evolution [new category perhaps multiple is more broadly appropriate]
--> Roche Lobe Overflow
--> Common Envelope Evolution
--> Tidal Interactions
--> (perhaps more?) 

Morgan

**Comment by katieefrey** [comment]
@morganemacleod 

Since you say "episodes" and "evolution" are synonymous in this context, then based on ADS, it looks like "Common envelope evolution" is favored with 260 refereed results for that phrase, while "Common envelope episodes" returns only 9.  I will add "episodes" as a non-preferred version though.

These concepts in this hierarchy seems fine...

Stellar physics | Stellar evolution | Multiple star evolution | Roche Lobe overflow    [I can add Related Term: Roche Lobe]
Stellar physics | Stellar evolution | Multiple star evolution | Common envelope evolution   [RT: Common envelope binaries]
Stellar physics | Stellar evolution | Multiple star evolution |

However, adding "Tidal interaction" is going to take some thought and discussion.

The concept already exists under...
Astrophysical processes | Gravitation | Newtonian gravitation | Gravitational interaction
and already has several child/grandchild concepts, including "Ocean tides" and "Atmospheric tides."

In a thesaurus such as the UAT, when a concept appears in multiple locations, it must bring all of its child concepts with it.  If we added "Tidal interaction" to this part of the hierarchy, we would end up with a situation that included...

Stellar Physics | Stellar Evolution | Multiple Star Evolution | Tidal interaction | Tides | Atmospheric tides
Stellar Physics | Stellar Evolution | Multiple Star Evolution | Tidal interaction | Tides | Ocean tides | Polar tides
Stellar Physics | Stellar Evolution | Multiple Star Evolution | Tidal interaction | Tides | Ocean tides

which clearly doesn't make any sense.

If having "Tidal interactions" under "Multiple star evolution" is warranted, we'll either need to re-work the suggested concept, or re-work the existing structure.  I'm not opposed to either option, but both of these cases usually take a bit of time to sort through, and right now I'm actually wrapping up suggestions for the next release (which will be out on Friday Dec 20).  If you want to pursue this (and those "perhaps more?" concepts you alluded to) I would be happy to open a new issue so they can be considered for the following release.

**Comment by katieefrey** [comment]
Changed described above have been implemented will be seen in the next release.

@morganemacleod As I mentioned above, if you want me to pursue adding a relationship between Tidal interactions and Multiple star evolution, please open a new issue which we can evaluate for a future release.  Thank you!

**Comment by morganemacleod** [comment]
Thank you!
