### ISSUE TITLE
New Concept: High Contrast Techniques

### ISSUE THREAD

**Issue by stlibrary8** [astrothesaurus/UAT#350]
High Contrast Techniques

High Contrast Techniques is meant to capture in a broad sense various high contrast methods for exoplanet detection. Term was suggested for addition by JWST scientist at Space Telescope Science Institute to add a level of description to UAT currently missing.

Suggested hierarchy:
Exoplanet astronomy --> Exoplanet detection methods --> **High contrast techniques** --> Coronagraphic imaging

Far infrared interferometry would sit at same level as new "High contrast techniques" term.

JWST scientist stated "High contrast imaging" is actually super specific. For this reason, recommend more generic "High contrast techniques" between detection methods and Coronagraphic imaging.

May consider additional child terms in future:
High contrast techniques --> High contrast imaging --> Coronagraphic imaging
High contrast techniques --> High contrast spectroscopy
Not yet needed.

https://ui.adsabs.harvard.edu/search/q=%22high%20contrast%20techniques%22%20exoplanet*&sort=date%20desc%2C%20bibcode%20desc&p_=0
https://ui.adsabs.harvard.edu/search/q=%22high%20contrast%20imaging%22%20exoplanet*&sort=date%20desc%2C%20bibcode%20desc&p_=0

**Comment by katieefrey** [comment]
currently the UAT has this structure:
Exoplanet astronomy --> Exoplanet detection methods --> Direct imaging --> Coronagraphic imaging
Exoplanet astronomy --> Exoplanet detection methods --> Direct imaging --> Far infrared interferometry

You say that "High contrast techniques" should be at the same level as Far infrared interferometry, so this is the hierarchy I see:

Exoplanet astronomy --> Exoplanet detection methods --> Direct imaging --> High contrast techniques --> Coronagraphic imaging
Exoplanet astronomy --> Exoplanet detection methods --> Direct imaging --> Far infrared interferometry

**Comment by stlibrary18** [comment]
Hi Katie, the above makes sense. I am confirming your breakdown after looking over my notes from Christine Chen and reviewing what was intended:

Exoplanet astronomy --> Exoplanet detection methods --> Direct imaging --> High contrast techniques --> Coronagraphic imaging

Exoplanet astronomy --> Exoplanet detection methods --> Direct imaging  --> Far infrared interferometry

AND ALSO

Exoplanet astronomy --> Exoplanet detection methods --> Direct imaging --> High contrast techniques --> High contrast spectroscopy (suggesting this third narrower term be added to v. 5.0 as well)

Here are some notes:
"Yes, I would like to see a "High Contrast" parent keyword to coronagraphic imaging as you describe. My immediate reaction is that it might be better to use the phrase "High Contrast Techniques" rather than "High Contrast Imaging". Imaging is really specific and does not capture the breadth of the high contrast techniques. For example, a lot of people do high contrast spectroscopy. High contrast spectroscopy is essentially the same as high contrast imaging; however, the imager is replaced by an integral field unit that provides spectra for every point on the sky." 

We did not specifically discuss "Far infrared interferometry", but looking at the literature, it's apparent it should be retained in the UAT as an exoplanet detection term in its own right. I hesitate to bucket it as another "High contrast technique" though and prefer it remain at the same level under "Direct imaging".

There should be a "Use for" entry under the new "High contrast techniques" term, i.e., "Use for _High contrast imaging_" with the understanding that "high contrast imaging" is a more specific term than "High contrast techniques" which may eventually warrant its own entry, but not now.

Another useful resource that helped me think about characterizing these terms and their relationships: https://subarutelescope.org/staff/guyon/15teaching.web/00AstrOptics.web/AstrOpt_19highcontrast.pdf
https://iopscience.iop.org/article/10.3847/1538-3881/abb5a3

Thank you!

**Comment by katieefrey** [comment]
Just in under the wire for the v5 release!
