### ISSUE TITLE
Modify Concept: Infrared astronomy

### ISSUE THREAD

**Issue by BartlettAstro** [astrothesaurus/UAT#414]
**Name the concept in question**
Infrared astronomy
http://astrothesaurus.org/uat/786

**Describe the change**
In Issue #76 
@katieefrey recommended that we add definition or scope note for the different types of astronomy (infrared, radio, ultraviolet, etc) under Observational astronomy > Methods.

originally submitted by François Ochsenbein (CDS)

@katieefrey found how about these definitions from Hubblesite.org?
http://hubblesite.org/reference_desk/faq/answer.php.id=70&cat=light
Infrared wavelengths span from 710 nm – 1 millimeter

**Please include any additional comments/feedback**
I am creating this issue to track only modification of infrared astronomy

**Comment by BartlettAstro** [comment]
Currently, Infrared astronomy has a definition without a bandpass.

Current definition
The study of infrared properties of astronomical objects.
     - An Etymological Dictionary of Astronomy and Astrophysics, by M. Heydari-Malayeri

Recommend definition
Infrared astronomy is "The study of infrared properties of astronomical objects."
- An Etymological Dictionary of Astronomy and Astrophysics, by M. Heydari-Malayeri

Infrared is "The invisible part of electromagnetic spectrum possessing wavelengths between those of visible light and those of radio waves, i.e. approximately between about 0.75 and 1000 μm."
- An Etymological Dictionary of Astronomy and Astrophysics, by M. Heydari-Malayeri

**Comment by BartlettAstro** [comment]
@danielchivvis I believe this is ready for PoolParty.

**Comment by katieefrey** [comment]
I think it would be cleaner to use this as the definition:

The study of infrared properties of astronomical objects. Infrared is the invisible part of electromagnetic spectrum possessing wavelengths between those of visible light and those of radio waves, i.e. approximately between about 0.75 and 1000 μm.


And then update the definition provenance to:
Modified from An Etymological Dictionary of Astronomy and Astrophysics, by M. Heydari-Malayeri


This way you get all the information across, but you aren't adding two seperate definitions to one concept when one of them doesn't specifically define the concept in question.  I updated the provenance to include "modified from" because the provided definition is no longer sourced verbatim from EDAA.

**Comment by danielchivvis** [comment]
Added revised definition.
