### ISSUE TITLE
Modify Concept: X-ray astronomy

### ISSUE THREAD

**Issue by ebortey** [astrothesaurus/UAT#419]
**Name the concept in question**
X-ray astronomy
http://astrothesaurus.org/uat/1810

**Describe the change**
In Issue #76 
@katieefrey recommended that we add definition or scope note for the different types of astronomy (infrared, radio, ultraviolet, etc) under Observational astronomy > Methods.

originally submitted by François Ochsenbein (CDS)

@katieefrey found these definitions from Hubblesite.org
http://hubblesite.org/reference_desk/faq/answer.php.id=70&cat=light
X-rays range in wavelength from 0.01 – 10 nm

**Please include any additional comments/feedback**
This issue has been created to track the modification of X-ray astronomy

**Comment by ebortey** [comment]
The current definition for the topic is: 
The study of celestial bodies using their X-ray emission. X-ray astronomy deals mainly with Galactic and extragalactic phenomena involving very high-energy photon emissions, covering a band of energies between 0.1 keV and 500 keV. The research field includes: X-ray binaries, cataclysmic variables, pulsars, black holes, dark matter, active galaxies, galactic clusters X-ray transients. The Earth's atmosphere absorbs most X-rays coming from outer space. X-ray astronomy therefore requires observations to be done above atmosphere. The first rocket flight which successfully detected a cosmic source of X-ray emission was launched in 1962 by an American research group. A very bright source was detected that they named Scorpius X-1. Since then several dedicated X-ray astronomy satellites have been launched, among which: Uhuru, INTEGRAL, ROSAT, Rossi X-ray Timing Explorer (RXTE), Chandra X-ray Observatory, and XMM-Newton, which have contributed to important advances in astronomy.
 	- An Etymological Dictionary of Astronomy and Astrophysics, by M. Heydari-Malayeri

This definition doesn't doesn't explain what X-rays are. 

I propose that the definition be:
X-ray astronomy is "the study of celestial bodies using their X-ray emission. X-ray astronomy deals mainly with Galactic and extragalactic phenomena involving very high-energy photon emissions, covering a band of energies between 0.1 keV and 500 keV. The research field includes: X-ray binaries, cataclysmic variables, pulsars, black holes, dark matter, active galaxies, galactic clusters X-ray transients. The Earth's atmosphere absorbs most X-rays coming from outer space. X-ray astronomy therefore requires observations to be done above atmosphere. The first rocket flight which successfully detected a cosmic source of X-ray emission was launched in 1962 by an American research group. A very bright source was detected that they named Scorpius X-1. Since then several dedicated X-ray astronomy satellites have been launched, among which: Uhuru, INTEGRAL, ROSAT, Rossi X-ray Timing Explorer (RXTE), Chandra X-ray Observatory, and XMM-Newton, which have contributed to important advances in astronomy."
 	- An Etymological Dictionary of Astronomy and Astrophysics, by M. Heydari-Malayeri

X-rays are "electromagnetic radiation with wavelengths shorter than that of ultraviolet radiation and greater than that of gamma rays. Typical X-rays have a wavelength ranging from 0.1 to 100 Å (0.01 to 10 nanometers), corresponding to frequencies in the range 3 × 10^16^ to 3 × 10^19^ Hz and energies in the range 100 eV to 100 keV. X-rays are produced artificially when high-speed electrons collide with a heavy metal target such as tungsten. Astrophysical sources of X-rays include plasmas with temperatures in the range 10^6^-10^8^ K, and deceleration process of rapidly moving charges upon interaction with matter (bremsstrahlung). X-rays were discovered in 1895 by Wilhelm Röntgen, a German physics professor (roentgen). For this discovery he won the first Nobel prize in physics in 1901."
 	- An Etymological Dictionary of Astronomy and Astrophysics, by M. Heydari-Malayeri

**Comment by BartlettAstro** [comment]
@danielchivvis @ebortey 

Possible shortened definition:

I propose that the definition be:
X-ray astronomy is "the study of celestial bodies using their X-ray emission. X-ray astronomy deals mainly with Galactic and extragalactic phenomena involving very high-energy photon emissions, covering a band of energies between 0.1 keV and 500 keV. The research field includes: X-ray binaries, cataclysmic variables, pulsars, black holes, dark matter, active galaxies, galactic clusters X-ray transients. The Earth's atmosphere absorbs most X-rays coming from outer space. X-ray astronomy therefore requires observations to be done above atmosphere.  ... "
- An Etymological Dictionary of Astronomy and Astrophysics, by M. Heydari-Malayeri

X-rays are "electromagnetic radiation with wavelengths shorter than that of ultraviolet radiation and greater than that of gamma rays. Typical X-rays have a wavelength ranging from 0.1 to 100 Å (0.01 to 10 nanometers), corresponding to frequencies in the range 3 × 1016 to 3 × 1019 Hz and energies in the range 100 eV to 100 keV. X-rays are produced artificially when high-speed electrons collide with a heavy metal target such as tungsten. Astrophysical sources of X-rays include plasmas with temperatures in the range 106-108K, and deceleration process of rapidly moving charges upon interaction with matter (bremsstrahlung). ..."
- An Etymological Dictionary of Astronomy and Astrophysics, by M. Heydari-Malayeri

I've taken the history out, much as I enjoy that. Using the definition for X-ray astronomy alone does technically answer the question the passbands because it gives that information in terms of an energy range, which is typical for the field. Using abbreviated versions of both definitions states the range in multiple units, including wavelength for consistency with similar descriptions.

**Comment by danielchivvis** [comment]
Removed content after "atmosphere. ..." in definition.
