### ISSUE TITLE
Clean up "Irregular galaxies," submitted by Sarah Weissman (STScI) 8/8/2016 

### ISSUE THREAD

**Issue by katieefrey** [astrothesaurus/UAT#9]
Cleaned up the "Irregular galaxies" category. The morphological classification of irregular galaxies typically contains three types Type 1 / magellanic irregular, type 2 / amorphous irregular and Dwarf Irregular. "I galaxies" isn't meaningful according to our scientists. We could add "Irr I galaxies" as a synonym for magellanic irregular and "Irr II galaxies" as a syonym for amorphus. (It's possible that "I galaxies" was supposed to mean "Irr I galaxies" but it's not clear to me.)
See:
https://ned.ipac.caltech.edu/level5/CLASSIFICATION/miag.html
https://en.wikipedia.org/wiki/Irregular_galaxy
Binney and Merrifield, Galactic Astronomy
https://en.wikipedia.org/wiki/Hubble_sequence

Irregular galaxies-->Magellanic irregular galaxies-->Magellanic Clouds-->Large Magellanic Cloud
Irregular galaxies-->Magellanic irregular galaxies-->Magellanic Clouds-->Magellanic Stream
Irregular galaxies-->Magellanic irregular galaxies-->Magellanic Clouds-->Small Magellanic Cloud
Irregular galaxies-->Magellanic irregular galaxies-->Magellanic Clouds
Irregular galaxies-->Magellanic irregular galaxies

**Comment by katieefrey** [comment]
Could the concept "Magellanic irregular galaxies" include concepts other than "Magellanic Clouds"? Or should one be a non-preferred version of the other?

**Comment by seweissman** [comment]
Yes. Magellanic irregular galaxies can include other concepts. The Magellanic Clouds are specific objects that are often cited as examples of irregular galaxies because they are visible to the unaided eye from earth. 

You can see a whole list of magellanic irregular galaxies at NED:
http://ned.ipac.caltech.edu/cgi-bin/OBJatt?delimiter=bar&nondb=row_count&crosid=objname&position=ra%2Cdec&enotes=objnote&position=pretype&position=z&position=zflag&attdat_CON=M&attdat_CON=S&attdat=attned&M=1149

**Comment by katieefrey** [comment]
I'm also thinking that the Magellanic Stream is also not really an irregular **galaxy** either, right?

How about this?
Local Group -->Magellanic Clouds-->Large Magellanic Cloud
Local Group -->Magellanic Clouds-->Magellanic Stream
Local Group -->Magellanic Clouds-->Small Magellanic Cloud
Local Group -->Magellanic irregular galaxies-->Small Magellanic Cloud
Irregular galaxies-->Magellanic irregular galaxies-->Small Magellanic Cloud

**Comment by seweissman** [comment]
_Magellanic irregular galaxies_ should go under _Irregular galaxies_, because this is one of the main types of irregular galaxies. https://ned.ipac.caltech.edu/level5/CLASSIFICATION/miag.html. Magellanic irregular are also known as Type I and Amorphous as Type II. It may be better to use Type I and Type II as the preferred terms. I'm not 100% sure. 

_Magellanic irregular galaxies_  should not go under _Local group_ because Magellanic irregular is a classification of galaxies and Local group is a specific group of galaxies. 

You can see a use of _Magellanic irregular galaxies_ referring to a general class of galaxies and not specifically the LMC or SMC in this paper: https://ui.adsabs.harvard.edu/#abs/1993PASP..105..374H/abstract

**Comment by katieefrey** [comment]
Ah, thanks for clarifying, I didn't quite catch the nuance of how "Magellanic irregular" was a descriptive class.  I'll look into the pref label issue you brought up, that's an easy change to make down the line, if need be.

Revised hierarchy:

Local Group -->Magellanic Clouds-->Large Magellanic Cloud
Local Group -->Magellanic Clouds-->Magellanic Stream
Local Group -->Magellanic Clouds-->Small Magellanic Cloud
Irregular galaxies-->Magellanic irregular galaxies (or Type I irregular galaxies) -->Small Magellanic Cloud
Irregular galaxies-->Amorphous irregular galaxies (or Type II irregular galaxies)

**Comment by katieefrey** [comment]
Above hierarchy implemented.
