### ISSUE TITLE
Cleaning up "Variable Stars," submitted by Sarah Weissman (STScI) 12/16/2016

### ISSUE THREAD

**Issue by katieefrey** [astrothesaurus/UAT#99]
KF: Picking up the thread from https://github.com/astrothesaurus/UAT/issues/16#issuecomment-268027204

===
Sarah Weissman:

I went through the list currently under Emission line stars that aren't already under variable stars.

I'm very sure that the following should be under variable stars:

    Luminous blue variables
    Me variable stars
    Z andromedae. They are a prototype for symbiotic stars but also variable: https://www.aavso.org/vsots_zand
    S Doradus stars. These should probably be under Luminous Blue Variables https://en.wikipedia.org/wiki/S_Doradus

I have questions about these:
Herbig Ae/Be - are sometimes variable?
"Sometimes Herbig Ae/Be stars show significant brightness variability. " https://en.wikipedia.org/wiki/Herbig_Ae/Be_star
"Virtually all Herbig Ae/Be stars observed are irregular variables (called 'UXors' after UX Ori), but there is a wide range of amplitudes from barely detectable to more than 4 mag in V. " (http://iopscience.iop.org/article/10.1086/300966/fulltext/)
So maybe UX Orionis aka UX Ori aka UXors are the subtype of Herbig Ae/Be that are variable and should be added as a term.

Wolf-Rayet
"Wolf–Rayet stars are massive hot stars that sometimes show variability," https://en.wikipedia.org/wiki/Variable_star
Should we add Wolf-rayet variable stars as a separate concept?

Here are some resources on variable stars
https://www.aavso.org/types-variables
https://en.wikipedia.org/wiki/Variable_star
https://www.aavso.org/variables-what-are-they-why-observe-them

Also it might be worthwhile to look for anything else in the thesaurus that has "variable" in the name and isn't in the variable stars hierarchy. Can you do a query like this in Pool Party?

====

**Comment by katieefrey** [comment]
In addition to the above, variable star-related concepts not currently found under "Variable stars" that need to be considered:

Algol variable stars
LB variable stars
Me variable stars
Peculiar variable stars
W Ursae Majoris variable stars
Early-type variable stars --> Beta Cephei stars
Early-type variable stars --> Luminous blue variable stars	
Early-type variable stars --> S Doradus stars
Early-type variable stars --> SX Arietis variable stars	
Early-type variable stars

**Comment by katieefrey** [comment]
Some thoughts....

Main sequence stars | Early-type main sequence stars | Beta Cephei variable stars
Main sequence stars | Early-type main sequence stars | SX Arietis variable stars

Variable stars | Intrinsic variable stars | Cataclysmic variable stars | Novae | Dwarf novae | SX Arietis variable stars
Variable stars | Intrinsic variable stars | Cataclysmic variable stars | Nova-like variable stars | UX Ursae Majoris stars
Variable stars | Intrinsic variable stars | Pulsating variable stars | Irregular variable stars | LB variable stars
Variable stars | Intrinsic variable stars | Pulsating variable stars | Irregular variable stars | LB variable stars (non-pref: TZ Cassiopeiae)

Variable stars | Extrinsic variable stars | Eclipsing binary stars | Algol variable stars

Variable stars | Peculiar variable stars

Variable stars | Early-type variable stars | Beta Cephei variable stars (non-pref: Beta Canis Majoris stars)
Variable stars | Early-type variable stars | S Doradus variable stars (non-pref: Luminous blue variable stars)
Variable stars | Early-type variable stars | SX Arietis variable stars

Variable stars | Late-type variable stars | Me variable stars
Variable stars | Late-type variable stars | LB variable stars

**Comment by katieefrey** [comment]
LB stars == luminous blue stars?

are all luminous blue stars also variable stars?

are Me stars all variable stars? Same with...
S Doradus
Beta lyrae
Upsilon Sagittari
S Vulpeculae
ZZ Ceti
PG 1159
WZ Sagittae
RRa/ab/b/c
Bailey type
T Tauri
Classical T Tauir
Weak-line T Tauri
UU Herculis
DQ Herculis
FU Orionis
AC Aurigae
Gamma Cassiopeaia
Delta cephei
BL Herculis
53 Persei
Am 
Alpha2 Canum Venaticorum
UV Ceti
BY Draconis
VY Sculpturis
UX Ursae Majoris
AM Canum Venaticorum
U Geminorum
Z Camelopardalis
((did I miss any??))
are those all always variable stars?  should I add "variable stars" after these designations?  My preference would YES to give the specific context.


AM Canum Venaticorum == Alpha2 Canum Venaticorum ???

Are early/late type variable stars... extrinsic or intrinsic? or periodic?

are Z Andromedae stars and RR Telescopii stars examples of symbiotic novae or just example of symbiotic binary stars?

are there symbiotic binary stars that are NOT symbiotic novae?

**Comment by katieefrey** [comment]
major rework of Variable stars section attached, testing what it would be like to remove some concepts and clean up the messy nesting.

Removed:
Pulsating variable stars
Periodic variable stars
Intrinsic variable stars
Extrinsic variable stars

These 4 all felt like artificial grouping categories with low relevant ADS results.  [see sheet1 of attached file]

Possibly I would like to also remove "long period variable stars", "Multi-periodic variable stars", "short period variable stars", and "Double-mode variable stars" [see sheet2 of attached file]

Is "Eruptive variable stars" synonymous with "Flare stars" ?

[variables_v2.xlsx](https://github.com/astrothesaurus/UAT/files/2337820/variables_v2.xlsx)

**Comment by katieefrey** [comment]
Ok, I've been talked off the ledge, even though Intrinsic and Extrinsic aren't used much in literature, they are useful categories for people who study variable stars.   Leaving the structure untouched, other than the questions [above](https://github.com/astrothesaurus/UAT/issues/99#issuecomment-413634621).

**Comment by rpoleski** [comment]
I have a number of comments. First, here are the things that I think are misguided:
- BL Her are not subtype of W Vir, these are 2 separate classes
- Delta Sct are not irregular, they are pulsating variable stars
- Mira variable are not irregular, they are pulsating variable stars
- Currently, all "RR Lyrae variable stars" are under "Double-mode variable stars". In fact, only RRd subtype stars are double mode. RRab and RRc are single mode. Also RRb type designations is not used in modern literature (I thought this issue was already resolved in UAT). Also I think "Bailey type stars" is synonymous to "RR Lyrae stars", not a subclass.

**Comment by katieefrey** [comment]
@rpoleski Thank you for your comments!

- BL Her are not subtype of W Vir, these are 2 separate classes
-- I've moved BL herc to be a direct child of Cepheid variable stars
- Delta Sct are not irregular, they are pulsating variable stars
--  I've made this adjustment
- Mira variable are not irregular, they are pulsating variable stars
-- I've made this adjustment
- Currently, all "RR Lyrae variable stars" are under "Double-mode variable stars". In fact, only RRd subtype stars are double mode. RRab and RRc are single mode. Also RRb type designations is not used in modern literature (I thought this issue was already resolved in UAT). Also I think "Bailey type stars" is synonymous to "RR Lyrae stars", not a subclass.
-- Yes, the merging of RRb and RRa into the single concept "RRab" is already implemented in the beta version of the UAT, I may have just missed that adjustment in any of the above working documents.  The same goes for Bailey type stars, that is now a NPT of "RR Lyrae stars."
-- I've moved "RR Lyrae" to be a direct child of "pulsating variable stars."  "RRd" is now also a direct child of "double-mode variable stars."

The attached spreadsheet should represent the current state of variable stars in the 3.0.0 beta.

I welcome any additional comments you have.  We're expecting to release 3.0.0 on September 21.

Do you have any thoughts on the usefulness of the concepts "Periodic variable stars," "semi-regular variable stars," "multi-periodic variable stars," "long period variable stars," and "short period variable stars"?

[variables_v3.xlsx](https://github.com/astrothesaurus/UAT/files/2375622/variables_v3.xlsx)

**Comment by stlibrary18** [comment]
Following up on issues/list noted above. Added comments after each and provided spreadsheet in OSF.

LB stars == luminous blue stars?
are all luminous blue stars also variable stars?: Yes, luminous blue [variable] stars is child of variable stars. Suggested placement is OSF spreadsheet.

are Me stars all variable stars? :
I’ve combed through print and online literature to find out more about “Me stars. 
Looks like not all (only many/most) Me stars are considered variable. Me classification is more about spectral class (evidence of hydrogen) than variability. Added addition polyhierarchical placement under Varible stars --> Intrinsic variable stars --> Long period variable stars --> Mira variable stars --> Me stars.

S Doradus: child term of “Luminous Blue variables”
Beta lyrae: all B lyrae are variables; agree with four placements. Depends if user wants to focus on binary nature or variability.
Upsilon Sagittari: Okay, current dual placement works well. 
S Vulpeculae: Suggest removing all instances. S Vul seems to refer to specific object, not a grouping of variable stars. Can find little in lit on S Vul object, much less mentions of a class or category of variables. S Vul is a particular star (pulsating, semi regular variable and also a giant star), not a type or subclass of stars.
ZZ Ceti: Okay, placement captures important characteristics: white dwarf, multi-periodic and pulsating
PG 1159: Okay, is a subclass of white dwarfs and type of multi-periodic pulsating variable
WZ Sagittae: Changed or removed placement in at least once instance. Refer to spreadsheet in OSF.
RRa/ab/b/c: RR Lyrae and Bailey are basically the same. Made significant changes to hierarchy for RR Lyr stars.
Bailey type: As far as I can tell, other way of describing RR Lyr stars. NPT for RR Lyrae.
T Tauri: Okay. Removed FU Ori as child term and recommended entering as RT instead.
Classical T Tauri: Okay. class of T Tauri based on width of spectral line in obs
Weak-line T Tauri: Okay. class of T Tauri based on width of spectral line in obs
UU Herculis: Repositioned this term in a few places. UU Herculis is semi-regular Srd type variable. Also considred double-mode. Removed from place as child term under “Irregular variable stars”.
DQ Herculis: Here's info I found. Still unsure about DQ Her. Removed incorrect placement under "slow novae" -- CV, eclipsing binary w white dwarf, fast spinning, magnetic, double-line eclipsing system, nova remnant, nova shell. “DQ Herculis is the prototype for a category of cataclysmic variable stars called intermediate polars. The system shows orbital period variation, possibly due to the presence of a third body”. “An Intermediate Polar (also called a DQ Herculis Star) is a type of cataclysmic variable binary star system with a white dwarf and a cool main-sequence secondary star. In most cataclysmic variables, matter from the companion star is gravitationally stripped by the compact star and forms an accretion disk around it. In intermediate polar systems, the same general scenario applies except that the inner disk is disrupted by the magnetic field of the white dwarf.”
FU Orionis: once thought to be a subtype of T Tauri (stage of T Tauri evolution). Now FU Orionis and T Tauri are distinct but related terms. FU Orionis should not be child term to T Tauri. Eruptive variable/flare star parent terms are correct
AC Aurigae: N/A, I searched for AC and RC Aurigae. Could not find significant mentions of AC Aur or RC Aur, if they are unique classes. Not sure where this term originated.
Gamma Cassiopeaia: eruptive irregular variables; rapidly rotating, hot shell; one text claims “nova-like variable”. Minor changes.
Delta cephei: recommend changing term in UAT to "Delta cepheids" to mean entire class, not one iconic object.
BL Herculis: Not a child of “W Virginis variable stars”, simply another type of “Cepheid variables”. “pulsating stars making up a subclass of Type II Cepheids”. 
53 Persei: Okay. type of B star and long period pulsating variable
Alpha2 Canum Venaticorum: Okay. helium-rich, ultra short period CV. Two white dwarfs. Recommend get rid of nova-like variable stars and leave as child of CV. 
UV Ceti
BY Draconis: Changes made. bright spot during rotation causes var. Literature questions whether true “flare star”. Back up one level to “eruptive variable stars” parent.
VY Sculpturis: Okay. A nova-like variable, aka anti-dwarf novae, CVs. Low-inclination system w/ massive white dwarf. 
UX Ursae Majoris: Okay. Eclipsing nova-like variable. Algol-like characteristics with extremely short periods. 
AM Canum Venaticorum: Okay. related to U Geminorum stars. Recommend get rid of nova-like variable stars and leave as child of CVs. Secondary white dwarf. Ultra short period variables (instead of nova-like variable stars). 
U Geminorum: Okay. Type of CV, known as dwarf novae;  semi-detached binary containing white dwarf.
Z Camelopardalis: “dwarf nova-type activity”; known for long irregular “stand still phase”.

((did I miss any??)): I don’t think our objective is to list all subclasses. If so, yes, there are lot that still need to be added. I am curious where this list and current variable star classes listed in the UAT came from.

are those all always variable stars? should I add "variable stars" after these designations? My preference would YES to give the specific context.: I don't think it's necessary to add "U Geminorum variable stars" instead of just "U Geminorum stars", for example. Seems to be a false way of labeling these types of stars.

AM Canum Venaticorum stars == Alpha2 Canum Venaticorum stars == AM stars ???: I couldn't really get to the bottom of this. AM Canum Venaticorum stars are distinct from Alpha2 Canum Venaticorum, but unsure about AM designation.

Are early/late type variable stars... extrinsic or intrinsic? or periodic?:
I couldn’t find a clean 1:1 comparison. Doesn’t seem we can say all early type are intrinsic and vice versa, for example, though it is suspected more early type stars vary in magnitude.

are Z Andromedae stars and RR Telescopii stars examples of symbiotic novae or just example of symbiotic binary stars?

Z Andromedae: symbiotic stars, interacting binaries

RR Telescopii seemed to refer to an object, not a class. Recommended removing.

are there symbiotic binary stars that are NOT symbiotic novae? : Okay. I believe current placement, with symbiotic novae as child term of symbiotic binary stars is most appropriate.

**Comment by katieefrey** [comment]
Following up on issues/list noted above. Added comments after each and provided spreadsheet in OSF.

LB stars == luminous blue stars?
- are LB stars the same as luminous blue stars?

are all luminous blue stars also variable stars?: Yes, luminous blue [variable] stars is child of variable stars. Suggested placement is OSF spreadsheet.
- updated

are Me stars all variable stars? :
I’ve combed through print and online literature to find out more about “Me stars.
Looks like not all (only many/most) Me stars are considered variable. Me classification is more about spectral class (evidence of hydrogen) than variability. Added addition polyhierarchical placement under Varible stars --> Intrinsic variable stars --> Long period variable stars --> Mira variable stars --> Me stars.
- as it turns out we had a concept called "Me variable stars"  so these are example of what the hierarchy is now:
[parent concepts] --> Variable stars --> Intrinsic variable stars --> Long period variable stars --> Mira variable stars --> Me variable stars
[parent concepts] --> M stars --> Me stars --> Me variable stars

S Doradus: child term of “Luminous Blue variables”
- accepted

Beta lyrae: all B lyrae are variables; agree with four placements. Depends if user wants to focus on binary nature or variability.
- accepted

Upsilon Sagittari: Okay, current dual placement works well.
S Vulpeculae: Suggest removing all instances. S Vul seems to refer to specific object, not a grouping of variable stars. Can find little in lit on S Vul object, much less mentions of a class or category of variables. S Vul is a particular star (pulsating, semi regular variable and also a giant star), not a type or subclass of stars.
ZZ Ceti: Okay, placement captures important characteristics: white dwarf, multi-periodic and pulsating
PG 1159: Okay, is a subclass of white dwarfs and type of multi-periodic pulsating variable
WZ Sagittae: Changed or removed placement in at least once instance. Refer to spreadsheet in OSF.
RRa/ab/b/c: RR Lyrae and Bailey are basically the same. Made significant changes to hierarchy for RR Lyr stars.
Bailey type: As far as I can tell, other way of describing RR Lyr stars. NPT for RR Lyrae.
T Tauri: Okay. Removed FU Ori as child term and recommended entering as RT instead.
Classical T Tauri: Okay. class of T Tauri based on width of spectral line in obs
Weak-line T Tauri: Okay. class of T Tauri based on width of spectral line in obs
UU Herculis: Repositioned this term in a few places. UU Herculis is semi-regular Srd type variable. Also considred double-mode. Removed from place as child term under “Irregular variable stars”.
DQ Herculis: Here's info I found. Still unsure about DQ Her. Removed incorrect placement under "slow novae" -- CV, eclipsing binary w white dwarf, fast spinning, magnetic, double-line eclipsing system, nova remnant, nova shell. “DQ Herculis is the prototype for a category of cataclysmic variable stars called intermediate polars. The system shows orbital period variation, possibly due to the presence of a third body”. “An Intermediate Polar (also called a DQ Herculis Star) is a type of cataclysmic variable binary star system with a white dwarf and a cool main-sequence secondary star. In most cataclysmic variables, matter from the companion star is gravitationally stripped by the compact star and forms an accretion disk around it. In intermediate polar systems, the same general scenario applies except that the inner disk is disrupted by the magnetic field of the white dwarf.”
FU Orionis: once thought to be a subtype of T Tauri (stage of T Tauri evolution). Now FU Orionis and T Tauri are distinct but related terms. FU Orionis should not be child term to T Tauri. Eruptive variable/flare star parent terms are correct
AC Aurigae: N/A, I searched for AC and RC Aurigae. Could not find significant mentions of AC Aur or RC Aur, if they are unique classes. Not sure where this term originated.
Gamma Cassiopeaia: eruptive irregular variables; rapidly rotating, hot shell; one text claims “nova-like variable”. Minor changes.
Delta cephei: recommend changing term in UAT to "Delta cepheids" to mean entire class, not one iconic object.
BL Herculis: Not a child of “W Virginis variable stars”, simply another type of “Cepheid variables”. “pulsating stars making up a subclass of Type II Cepheids”.
53 Persei: Okay. type of B star and long period pulsating variable
Alpha2 Canum Venaticorum: Okay. helium-rich, ultra short period CV. Two white dwarfs. Recommend get rid of nova-like variable stars and leave as child of CV.
UV Ceti
BY Draconis: Changes made. bright spot during rotation causes var. Literature questions whether true “flare star”. Back up one level to “eruptive variable stars” parent.
VY Sculpturis: Okay. A nova-like variable, aka anti-dwarf novae, CVs. Low-inclination system w/ massive white dwarf.
UX Ursae Majoris: Okay. Eclipsing nova-like variable. Algol-like characteristics with extremely short periods.
AM Canum Venaticorum: Okay. related to U Geminorum stars. Recommend get rid of nova-like variable stars and leave as child of CVs. Secondary white dwarf. Ultra short period variables (instead of nova-like variable stars).
U Geminorum: Okay. Type of CV, known as dwarf novae; semi-detached binary containing white dwarf.
Z Camelopardalis: “dwarf nova-type activity”; known for long irregular “stand still phase”.
- thanks for looking into all of these

((did I miss any??)): I don’t think our objective is to list all subclasses. If so, yes, there are lot that still need to be added. I am curious where this list and current variable star classes listed in the UAT came from.
- We don't want to list all subclasses, in fact we may be including too many as it is.  The variable star classes listed in UAT were there when we received the merged thesaurus.  I believe most originate from the IAU and IVOA thesauri, although I can't say that for sure.  As for this specific list, I was trying to list all subclasses of stars currently in the "variable star" section of the UAT that did not specifically include the word "variable" in their concept name.  Uncertain whether it would be useful to specify "variable" or not... at first I was thinking yes, I should add that, but now I'm leaning more towards no.

are those all always variable stars? should I add "variable stars" after these designations? My preference would YES to give the specific context.: I don't think it's necessary to add "U Geminorum variable stars" instead of just "U Geminorum stars", for example. Seems to be a false way of labeling these types of stars.

AM Canum Venaticorum stars == Alpha2 Canum Venaticorum stars == AM stars ???: I couldn't really get to the bottom of this. AM Canum Venaticorum stars are distinct from Alpha2 Canum Venaticorum, but unsure about AM designation.
- thank you for looking into this!

Are early/late type variable stars... extrinsic or intrinsic? or periodic?:
I couldn’t find a clean 1:1 comparison. Doesn’t seem we can say all early type are intrinsic and vice versa, for example, though it is suspected more early type stars vary in magnitude.
- thanks for looking into this too!

are Z Andromedae stars and RR Telescopii stars examples of symbiotic novae or just example of symbiotic binary stars?
Z Andromedae: symbiotic stars, interacting binaries
RR Telescopii seemed to refer to an object, not a class. Recommended removing.
-sounds good, thanks!

are there symbiotic binary stars that are NOT symbiotic novae? : Okay. I believe current placement, with symbiotic novae as child term of symbiotic binary stars is most appropriate.
- thanks!

**Comment by rpoleski** [comment]
@katieefrey the v3 document you've linked has Intrinsic/Extrinsic division - I thought it was decided to be removed (and I'm for removing it). 

I think there are missing types: 

- RV Tau - they are a subtype of Cepheids,
- gamma Dor - pulsating variable stars, may be considered short-period.

I also thought that roAp (rapidly oscillating Ap stars), but I've found they are the same as alpha2 CVn. I think roAp is more commonly used nowadays and better, because it's descriptive.

Also I'd like to mention a few resources that may be used to solve naming issues:

- [GCVS variability types](http://www.sai.msu.su/gcvs/gcvs/iii/vartype.txt) - from there it seems that Z And stars are the same as symbiotic stars,
- [paper](https://arxiv.org/abs/1602.04964) which has quite many variable type in first figure,
- [paper](https://arxiv.org/abs/0712.3797) that has frequently used graphic and number of stars of different types,
- [AAVSO catalog](https://www.aavso.org/vsx/) - I guess one can extract statistics on variable types from there, to decide which types are worth being present in UAT,
- "Light Curves Of Variable Stars: A Pictorial Atlas" by Sterken and Jaschek book - it was published some years ago, but I think that still should be useful to resolve the issues raised here.

**Comment by katieefrey** [comment]
@rpoleski We're keeping Intrinsic/Extrinsic at the moment.  Although I tend to dislike the concepts myself, I think removing them would warrant extensive discussion; they seem to be useful categories for many people.

The two concepts you suggested have decent usage in the literature, so I've added them.

It does look like roAp or rapidly oscillating Ap stars is used more frequently in ADS than alpha2 CVn, and I've confirmed that they are the same thing.  I've updated the preferred term for this concept.

**Comment by rpoleski** [comment]
One more group missing are anomalous Cepheids also known as BL Boo stars. They should be under "Cepheid variable stars".

In lines 50 and 51 there are stars that are "Long period" and "Slow irregular". I'm not sure we can classify some phenomenon as periodic and irregular at the same time. 
Ohhh... I see similar combination in lines 71-83. What is the logic behind this?

I've looked at semi-regular stars and found them under:

 - Intrinsic variable stars | Long period variable stars | Semi-regular variable stars | 
 - Intrinsic variable stars | Pulsating variable stars | Long period variable stars | Semi-regular variable stars
 - Intrinsic variable stars | Pulsating variable stars | Semi-regular variable stars |  
 - Periodic variable stars | Long period variable stars | Semi-regular variable stars |  
 - Periodic variable stars | Semi-regular variable stars |  

Honestly, I don't see what is the reasoning behind all of this. Is there any star that belongs to one of these categories, but does not belong to other? 
I propose to leave only the second version from above and delete all other.

**Comment by katieefrey** [comment]
@rpoleski I think I came to that conclusion at some point as well, although we are keeping the "periodic variable stars" sub-branch, so we're using your 2nd and 4th bullet.  Attached is a more recent variable stars section.

I'll look into your comment about BL Boo stars tomorrow!

Tomorrow is my hard cut off date for changes for the 3.0 release, so please reply soon if you have any final thoughts.  Even then I can't grantee I'll be able to fit anything new into 3.0, but the UAT is intended to the iterative and improving; there will be another new version.

[3.0variable.xlsx](https://github.com/astrothesaurus/UAT/files/2398740/3.0variable.xlsx)

**Comment by rpoleski** [comment]
I'd like to give arguments for removing intrinsic/extrinsic level. First, it's hard to classify a variable star as intrinsic/extrinsic (level 4) if we don't know if it's eclipsing, ellipsoidal, cataclysmic, eruptive, magnetic, or pulsating (these are level 5). Second, in the current version, level 4 also contains "Periodic variable stars" but these are repeated entries mostly from pulsating category. The only other record is WZ Sge, but considering them periodic is problematic in my opinion. Many of them have only 2 episodes observed, so it's hard to claim there is any period at all. If WZ Sge are periodic, then U Gem and SU UMa should be as well. Third, currently extrinsic variables are divided only into eclipsing and ellipsoidal. Considering ellipsoidal variables as extrinsic is problematic - ellipsoidal variables have shape changed by the external force, but what we observe is the change of the shape itself. The change of the shape seems something intrinsic even if caused by extrinsic force.

Please remove roAp from cataclysmic variables.

I've checked anomalous Cepheids - there are at least 300 of them known and they're considered a separate class for at least 20 years.

**Comment by katieefrey** [comment]
I removed roAp from Cataclysmic.

Added BL Boo but with a preferred term of "Anomalous Cepheid variable stars" since that was used more frequently in ADS than BL Boo/Bootis.

I took WZ Sge out of periodic.

Leaving intrinsic/extrinsic in for the current release, and closing this issue since its being release tomorrow, but I will copy your comments on that into a new issue for further discussion.
